### ISSUE TITLE
synapse-get-tool passes synapseCache instead of retrieved file in Rabix

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks-Workflows/dockstore-tool-synapseclient#13]
Running with cwl-runner I do not have this issue. When I test my workflow in Rabix, synapse-get-tool passes the synapseCache instead of the downloaded file to the next tool (an R script, which errors like so):

`1: In file(file, "rt") :
  'raw = FALSE' but '/Users/rallaway/RabixComposer/Executions/local/dose-response-metric-workflow/2019-06-13-10-41-44/app-2019-06-13-104145.764/root/get_data/.synapseCache' is not a regular file
2: In file(file, "rt") :
  cannot open file '/Users/rallaway/RabixComposer/Executions/local/dose-response-metric-workflow/2019-06-13-10-41-44/app-2019-06-13-104145.764/root/get_data/.synapseCache': it is a directory
Execution halted`

**Comment by thomasyu888** [comment]
@allaway Can you help me reproduce this issue?

**Comment by allaway** [comment]
TBH I haven't used Rabix for a long time. I would suggest if this works with cwl-runner, that whatever the bug is it's a bug with Rabix and not the tool, so this should be closed.
