### ISSUE TITLE
All tools should run in a container

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks-Workflows/dockstore-tool-synapseclient#2]
This will usually mean inserting a 
```
hints:
  DockerRequirement:
    dockerPull: sagebionetworks/synapsepythonclient
```
in each file and changing the `baseCommand` to `python3.6`

**Comment by kdaily** [comment]
Fixed with https://github.com/Sage-Bionetworks/synapse-workflow-cwl-tools/commit/8910c9f852b10eedc661a2a4eb0e737a865ca5e1. Will document!
