### ISSUE TITLE
Fileview munging generic enough for this repo?

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks-Workflows/dockstore-tool-synapseclient#8]
I've built a tool (and python script) that takes in a table of clinical annotations and joins them to synapse ids to build a manifest. Do we think that it's generic enough for this repo?
https://github.com/sgosline/NEXUS/blob/master/bin/rna-seq-workflow/join-fileview-by-specimen-tool.cwl

If so we can add the python script to the docker image that will hopefully accompany these scripts. (that currently exists in mine and @andrewelamb 's imagination).

**Comment by sgosline** [comment]
Updated with PR #9

**Comment by thomasyu888** [comment]
Fileview munging has its own Dockerfile so it should live in another repo.
